apiVersion: apps/v1
kind: Deployment
metadata:
  name: filecodebox
  namespace: app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filecodebox
  template:
    metadata:
      labels:
        app: filecodebox
    spec:
      containers:
        - name: filecodebox
          image: lanol/filecodebox:edge-c676458
          ports:
            - containerPort: 12345
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          livenessProbe:
            tcpSocket:
              port: 12345
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 12345
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: filecodebox-data
