apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filecodebox-data
  namespace: app-dev
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
